import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { listDocuments, parseAnnotatedMarkdown, readDocument, saveAnnotatedDocument, saveDocument } from '../src/documents.mjs'
import { annotationSchema, validateAnnotationMetadata } from '../src/annotations.mjs'

test('document API lists, reads and hash-guards canonical Markdown',async()=>{const root=mkdtempSync(join(tmpdir(),'holoself-doc-'));mkdirSync(join(root,'profile'));writeFileSync(join(root,'profile','identity.md'),'# Me\n');const [item]=listDocuments(root);assert.equal(item.path,'profile/identity.md');const read=readDocument(root,item.path);const saved=await saveDocument(root,item.path,'# Me\n\nUpdated\n',read.hash);assert.notEqual(saved.hash,read.hash);await assert.rejects(()=>saveDocument(root,item.path,'bad',read.hash),/changed on disk/);assert.throws(()=>readDocument(root,'../secret.md'),/escapes|not found/)})

test('annotated editor preserves protected frontmatter and section markers',async()=>{const root=mkdtempSync(join(tmpdir(),'holoself-doc-'));mkdirSync(join(root,'profile'));const path=join(root,'profile','identity.md'),content='---\nschema_version: 1\naccess_lenses: [general, private]\ndisclosure: internal-only\nsensitivity: personal\ndocument_role: content\nconfidence: confirmed\nvisibility: private\npublic_safe: false\ncustom_key: preserved\n---\n# Identity\n<!-- os-section: values -->\nOriginal values\n';writeFileSync(path,content);const read=readDocument(root,'profile/identity.md');assert.deepEqual(read.annotations.metadata.access_lenses,['general','private']);const segments=read.annotations.segments.map(segment=>({...segment,content:segment.annotation==='values'?'\nUpdated values\n':segment.content}));await saveAnnotatedDocument(root,'profile/identity.md',{metadata:{...read.annotations.metadata,confidence:'mixed'},segments,expectedHash:read.hash});const saved=readFileSync(path,'utf8');assert.match(saved,/custom_key: preserved/);assert.match(saved,/<!-- os-section: values -->/);assert.match(saved,/confidence: mixed/);assert.match(saved,/Updated values/);await assert.rejects(()=>saveAnnotatedDocument(root,'profile/identity.md',{metadata:read.annotations.metadata,segments:segments.filter(segment=>!segment.annotation),expectedHash:readDocument(root,'profile/identity.md').hash}),/section annotations cannot/)})

test('annotation schema guides values and rejects unsafe combinations',()=>{const schema=annotationSchema([{id:'general',title:'General',source:'builtin'},{id:'custom',title:'Custom',source:'custom'}]);assert.equal(schema.fields.access_lenses.type,'multi-select');assert.deepEqual(schema.fields.disclosure.options,['internal-only','review-required','publish-approved']);assert.deepEqual(schema.fields.document_role.options,['policy','evidence','content']);const valid=validateAnnotationMetadata({access_lenses:['general','legacy-lens'],disclosure:'review-required',sensitivity:'personal',document_role:'evidence',confidence:'confirmed',visibility:'private'},['general']);assert.equal(valid.valid,true);assert.deepEqual(valid.unknown_lenses,['legacy-lens']);assert.match(valid.warnings.join(' '),/legacy-lens/);const confidential=validateAnnotationMetadata({access_lenses:['general'],disclosure:'publish-approved',sensitivity:'compensation-confidential',document_role:'content'},['general']);assert.equal(confidential.valid,false);assert.match(confidential.errors.join(' '),/publish-approved/);const conflict=validateAnnotationMetadata({access_lenses:['general'],disclosure:'internal-only',sensitivity:'personal',document_role:'content',public_safe:true},['general']);assert.equal(conflict.valid,false);assert.match(conflict.errors.join(' '),/public_safe/);const empty=validateAnnotationMetadata({access_lenses:[],disclosure:'internal-only',sensitivity:'personal',document_role:'content'},['general']);assert.equal(empty.valid,false)})

test('document save restores exact bytes when validation fails',async()=>{const root=mkdtempSync(join(tmpdir(),'holoself-doc-'));mkdirSync(join(root,'profile'));const path=join(root,'profile','identity.md');writeFileSync(path,'# Original\r\n');const read=readDocument(root,'profile/identity.md');await assert.rejects(()=>saveDocument(root,'profile/identity.md','# Invalid\n',read.hash,{validate:async()=>{throw new Error('invalid')}}),/original content restored/);assert.equal(readFileSync(path,'utf8'),'# Original\r\n')})
