import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { run } from '../src/cli.mjs'
import { contextData, holoselfMcpSearch } from '../src/ecosystem.mjs'
import { createMcpSession } from '../src/mcp-server.mjs'
async function capture(fn){const old=console.log;let out='';console.log=(...args)=>out+=args.join(' ')+'\n';try{await fn();return out}finally{console.log=old}}
async function fixture(){const root=await mkdtemp(join(tmpdir(),'holoself-domains-')),self=join(root,'self'),consumer=join(root,'consumer'),peer=join(root,'peer');await mkdir(consumer);await mkdir(peer);await capture(()=>run(['init','--root',self]));await writeFile(join(self,'context','self-evidence.md'),'---\naccess_lenses: [general, professional, private]\ndisclosure: review-required\nsensitivity: personal\ndocument_role: evidence\n---\n# Self evidence\n\nDurableSelfSentinel measured achievement.\n');for(const project of [consumer,peer]){await writeFile(join(project,'domain.md'),'# Domain\n\nDomainSentinel private workflow.\n');await capture(()=>run(['link','add','--self',self,'--project',project,'--lens','professional','--secondary-lenses','general','--project-include','**/*.md','--yes','--no-activate']))}return {root,self,consumer,peer}}
test('legacy federation flags return positive self context and exclude every domain on cold and warm requests',async()=>{const {root,consumer,peer}=await fixture();try{for(const options of [{},{federated:true},{spaces:[peer],federated:true}])for(let round=0;round<2;round++){const data=contextData({project:consumer,task:'measured achievement',...options});assert.ok(data.self.documents.some(doc=>doc.content.includes('DurableSelfSentinel')));assert.deepEqual(data.project.documents,[]);assert.deepEqual(data.federated,[]);assert.doesNotMatch(JSON.stringify(data),/DomainSentinel/)}await rm(peer,{recursive:true,force:true});const data=contextData({project:consumer,federated:true});assert.ok(data.self.documents.length>0);assert.deepEqual(data.unreachable_spaces||[],[])}finally{await rm(root,{recursive:true,force:true})}})
test('CLI and MCP search share self-only retrieval and linked private denial',async()=>{const {root,consumer}=await fixture();try{const cli=JSON.parse(await capture(()=>run(['search','DurableSelfSentinel','--project',consumer,'--federated'])));assert.ok(cli.results.length>0);assert.ok(cli.results.every(result=>result.source_kind==='self'));assert.deepEqual(holoselfMcpSearch(consumer,{query:'DomainSentinel',federated:true}).results,[]);await assert.rejects(run(['search','DurableSelfSentinel','--project',consumer,'--lens','private']),/not granted/);const outputs=[],m=createMcpSession({project:consumer,write:line=>outputs.push(JSON.parse(line))});m(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'synthetic',version:'1'}}}));m(JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'holoself_context',arguments:{task:'measured achievement'}}}));const result=outputs.at(-1);assert.equal(result.result.isError,undefined);assert.match(JSON.stringify(result),/DurableSelfSentinel/);assert.doesNotMatch(JSON.stringify(result),/DomainSentinel/)}finally{await rm(root,{recursive:true,force:true})}})

test('linked self authority fails closed for revocation, salt mismatch and malformed attestation registry',async()=>{
 const {root,self,consumer}=await fixture(),file=join(self,'.holoself','links.json'),original=await readFile(file,'utf8'),registry=JSON.parse(original)
 try{for(const mutate of [value=>value.links.forEach(entry=>entry.status='revoked'),value=>value.links.forEach(entry=>entry.binding_salt='wrong'),()=>null]){const value=JSON.parse(original),changed=mutate(value);await writeFile(file,JSON.stringify(changed===null?{schema_version:1,links:'broken'}:value));assert.throws(()=>contextData({project:consumer,task:'measured achievement'}),/revoked|salt|registry|attest|link/i);assert.throws(()=>holoselfMcpSearch(consumer,{query:'DurableSelfSentinel'}),/revoked|salt|registry|attest|link/i);await assert.rejects(run(['search','DurableSelfSentinel','--project',consumer]),/revoked|salt|registry|attest|link/i)}await writeFile(file,original);assert.ok(contextData({project:consumer,task:'measured achievement'}).self.documents.length)}finally{await rm(root,{recursive:true,force:true})}
})
