import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('Workbench ships complete local branded navigation',()=>{const html=readFileSync(new URL('../web/index.html',import.meta.url),'utf8');for(const label of ['Spaces','Lenses','Knowledge','Review','Conversations','Setup'])assert.match(html,new RegExp(label));assert.match(html,/https:\/\/www\.movetheneedle\.info/);assert.match(html,/Built and sponsored by Move the Needle/);assert.doesNotMatch(html,/https:\/\/(?!www\.movetheneedle\.info)/)})
test('visual system includes accessibility, responsive behavior, and font icons',()=>{const css=readFileSync(new URL('../web/styles.css',import.meta.url),'utf8');assert.match(css,/--ink:#10231d/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/:focus-visible/);assert.match(css,/@media\(max-width:850px\)/);assert.match(css,/Segoe UI Symbol/);assert.match(css,/\.folder-tree/);assert.match(css,/\.knowledge-group/)})
test('Workbench exposes complete guarded workflows',()=>{const app=readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8');for(const capability of ['Create custom lens','Validate and save','Review proposal','Approve exact change','data-remove-space','Fine-tune instructions','Open here','Review structured knowledge changes','Draft preserved','included scope\\(s\\)','index_exists'])assert.match(app,new RegExp(capability));assert.match(app,/\/api\/connectors/);assert.match(app,/previewHash/);assert.match(app,/Recent conversations/);assert.match(app,/data-conversation/);assert.doesNotMatch(app,/\/api\/command/)})
test('Workbench provides lazy folder browsing, canonical discovery, and typed knowledge groups',()=>{const app=readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8');for(const text of ['Browse local folders lazily','manual absolute path','Discover existing links','Spaces connect project purpose','Profile','Context','Topics','Reference','Local contributions','Filter knowledge files'])assert.match(app,new RegExp(text));assert.match(app,/\/api\/filesystem\/folders/);assert.match(app,/data-folder-path/);assert.match(app,/data-knowledge-group/)})
test('annotation editor uses dynamic guided controls and inline policy validation',()=>{const app=readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8'),css=readFileSync(new URL('../web/styles.css',import.meta.url),'utf8');for(const value of ['/api/annotations/schema','data-access-lens','annotation-disclosure','data-annotation-field="sensitivity"','confidence-values','Derived from disclosure','annotation-policy','validateAnnotationForm'])assert.match(app,new RegExp(value));assert.doesNotMatch(app,/id="a-access"/);assert.match(css,/\.lens-options/);assert.match(css,/\.annotation-policy\.invalid/)})

test('dialog close cannot be mistaken for document or harness actions',()=>{const html=readFileSync(new URL('../web/index.html',import.meta.url),'utf8'),app=readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8');assert.match(html,/type="button" class="close" id="dialog-close"/);assert.match(app,/delete dialog\.dataset\.doc/);assert.match(app,/button\[data-doc\]/);assert.match(app,/dialog-close/);assert.doesNotMatch(app,/closest\('\[data-doc\]'\)/)})
test('proposal review presents structured user-facing sections',()=>{const app=readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8'),css=readFileSync(new URL('../web/styles.css',import.meta.url),'utf8');for(const label of ['Review proposal','TARGET DOCUMENT','SOURCE EVIDENCE','Knowledge to add','affectedFiles'])assert.match(app,new RegExp(label));assert.doesNotMatch(app,/\$\{esc\(d\.preview\)\}/);assert.match(css,/\.review-meta/);assert.match(css,/\.review-change/)})
test('connector setup exposes automatic CLI, terminal, GUI capabilities and extensions',()=>{const app=readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8');for(const label of ['Detected built-ins work without setup','CLI connectors','Terminal hosts','GUI applications','connectors/\\*\\.json'])assert.match(app,new RegExp(label));assert.match(app,/connector-table/);assert.match(app,/data-launch/);assert.match(app,/item\.capabilities/)})
