import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { delimiter, extname, isAbsolute, join, resolve } from 'node:path'
import { spawn, spawnSync } from 'node:child_process'
import { detectHarnesses, validateHarnessConfig } from './harnesses.mjs'

const TERMINALS=[
 {id:'windows-terminal',name:'Windows Terminal',candidates:['wt.exe',join(process.env.LOCALAPPDATA||'', 'Microsoft','WindowsApps','wt.exe')],capabilities:['terminal','working-directory','launch-command']},
 {id:'powershell-7',name:'PowerShell 7',candidates:['pwsh.exe'],capabilities:['terminal','working-directory','launch-command']},
 {id:'windows-powershell',name:'Windows PowerShell',candidates:['powershell.exe'],capabilities:['terminal','working-directory','launch-command']},
 {id:'command-prompt',name:'Command Prompt',candidates:['cmd.exe'],capabilities:['terminal','working-directory','launch-command']}
]
const GUI_APPS=[
 {id:'claude-desktop',name:'Claude',appIds:['Claude_pzs8sxrjxfjjc!Claude'],capabilities:['gui','conversation']},
 {id:'codex-app',name:'Codex App',appIds:['OpenAI.Codex_2p2nqsd0c76g0!App'],viaCli:'codex',capabilities:['gui','working-directory','open-project']},
 {id:'chatgpt-classic',name:'ChatGPT Classic',appIds:['OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0!ChatGPT'],capabilities:['gui','conversation']}
]
function pathCandidates(name,env=process.env){const dirs=(env.PATH||'').split(process.platform==='win32'?';':delimiter),exts=process.platform==='win32'?(env.PATHEXT||'.EXE;.CMD;.BAT').split(';'):[''];return dirs.flatMap(dir=>[join(dir,name),...exts.map(ext=>join(dir,extname(name)?name:name+ext.toLowerCase()))])}
function findExecutable(names,env=process.env){for(const name of names)for(const path of (isAbsolute(name)?[name]:pathCandidates(name,env)))if(existsSync(path)&&lstatSync(path).isFile()&&!['.cmd','.bat'].includes(extname(path).toLowerCase()))return path;if(process.platform==='win32'){for(const name of names.filter(value=>!isAbsolute(value))){const found=spawnSync('where.exe',[name],{encoding:'utf8',windowsHide:true,timeout:3000}).stdout?.split(/\r?\n/).find(Boolean);if(found)return found}}return null}
function startApps(){if(process.platform!=='win32')return new Map();try{const script='Get-StartApps | Select-Object Name,AppID | ConvertTo-Json -Compress',out=spawnSync('powershell.exe',['-NoProfile','-Command',script],{encoding:'utf8',windowsHide:true,timeout:5000}),rows=JSON.parse(out.stdout||'[]');return new Map((Array.isArray(rows)?rows:[rows]).map(row=>[row.AppID,row.Name]))}catch{return new Map()}}
function extensionFiles(root){const dir=join(root,'connectors');if(!existsSync(dir))return [];return readdirSync(dir).filter(name=>name.endsWith('.json')).sort().map(name=>{const path=join(dir,name),stat=lstatSync(path);if(stat.isSymbolicLink()||!stat.isFile())throw new Error(`unsafe connector entry: ${path}`);let value;try{value=JSON.parse(readFileSync(path,'utf8'))}catch(error){throw new Error(`invalid connector ${name}: ${error.message}`)};return validateConnector(value,name)})}
export function validateConnector(value,file='connector'){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${file}: connector must be an object`);if(value.schema_version!==1)throw new Error(`${file}: schema_version must be 1`);if(!['cli','terminal','gui'].includes(value.kind))throw new Error(`${file}: invalid connector kind`);if(!/^[a-z][a-z0-9-]{1,39}$/.test(value.id||''))throw new Error(`${file}: invalid connector id`);if(typeof value.name!=='string'||!value.name.trim())throw new Error(`${file}: connector name required`);if(value.executable!==undefined&&(!isAbsolute(value.executable)||!existsSync(value.executable)))throw new Error(`${file}: executable must be an existing absolute path`);for(const key of ['arguments','interactive_arguments'])if(value[key]!==undefined&&(!Array.isArray(value[key])||value[key].some(item=>typeof item!=='string')))throw new Error(`${file}: ${key} must be string array`);return {schema_version:1,kind:value.kind,id:value.id,name:value.name.trim(),executable:value.executable||null,arguments:value.arguments||[],interactive_arguments:value.interactive_arguments||[],prompt_transport:value.prompt_transport||'argument',capabilities:Array.isArray(value.capabilities)?value.capabilities:[],app_id:value.app_id||null,automatic:false,source:'root-extension'}}
export function saveConnectorExtension(root,value){const connector=validateConnector(value),dir=join(root,'connectors'),path=join(dir,`${connector.id}.json`),tmp=`${path}.tmp-${process.pid}`;mkdirSync(dir,{recursive:true});try{writeFileSync(tmp,JSON.stringify(connector,null,2)+'\n');renameSync(tmp,path)}finally{if(existsSync(tmp))rmSync(tmp,{force:true})}return connector}
export function loadConnectors(root,env=process.env){const cli=detectHarnesses(env).map(item=>({schema_version:1,kind:'cli',id:item.id,name:item.id==='pi'?'PI':item.id[0].toUpperCase()+item.id.slice(1),detected:item.detected,available:Boolean(item.defaultConfiguration),executable:item.defaultConfiguration?.executable||null,arguments:item.defaultConfiguration?.arguments||[],interactive_arguments:item.defaultConfiguration?.arguments?.slice(0,-1).filter(arg=>!['--print','--no-session','exec','-p'].includes(arg))||[],prompt_transport:'argument',capabilities:['conversation','interactive-terminal'],automatic:true,source:'builtin'}));const terminal=TERMINALS.map(item=>{const executable=findExecutable(item.candidates,env);return {...item,schema_version:1,kind:'terminal',detected:Boolean(executable),available:Boolean(executable),executable,automatic:true,source:'builtin'}});const apps=startApps(),gui=GUI_APPS.map(item=>{const cliConnector=cli.find(connector=>connector.id===item.viaCli),appId=item.appIds.find(id=>apps.has(id));return {...item,schema_version:1,kind:'gui',detected:Boolean(appId||cliConnector?.available),available:Boolean(appId||cliConnector?.available),app_id:appId||null,via_cli:item.viaCli||null,automatic:true,source:'builtin'}});const merged=[...cli,...terminal,...gui];for(const extension of extensionFiles(root)){const index=merged.findIndex(item=>item.id===extension.id);if(index>=0)merged[index]={...merged[index],...extension,detected:true,available:true};else merged.push({...extension,detected:true,available:true})}return merged}
function terminalArgs(terminal,cwd,command,args=[]){if(terminal.id==='windows-terminal')return ['-d',cwd,command,...args];if(terminal.id==='powershell-7'||terminal.id==='windows-powershell')return command?['-NoExit','-Command','&',command,...args]:['-NoExit'];if(terminal.id==='command-prompt')return command?['/K',command,...args]:['/K'];return [...(terminal.arguments||[]).map(arg=>arg.replace('{cwd}',cwd).replace('{command}',command)),...args]}
export function connectorLaunchPlan(connectors,{space,connectorId,terminalId,mode}){const connector=connectors.find(item=>item.id===connectorId),cwd=resolve(space);if(!connector?.available)throw new Error('connector unavailable');if(mode==='gui'){if(connector.via_cli){const cli=connectors.find(item=>item.id===connector.via_cli);if(!cli?.available)throw new Error('GUI launcher CLI unavailable');return {executable:cli.executable,arguments:[...(cli.interactive_arguments||[]),'app'],cwd,detached:true}}if(connector.app_id)return {executable:join(process.env.WINDIR||'C:/Windows','explorer.exe'),arguments:[`shell:AppsFolder\\${connector.app_id}`],cwd,detached:true};throw new Error('GUI launch unavailable')}const terminal=connectors.find(item=>item.id===terminalId);if(!terminal?.available||terminal.kind!=='terminal')throw new Error('terminal unavailable');if(mode==='terminal')return {executable:terminal.executable,arguments:terminalArgs(terminal,cwd,'',[]).filter(Boolean),cwd,detached:true};if(connector.kind!=='cli')throw new Error('interactive launch requires CLI connector');return {executable:terminal.executable,arguments:terminalArgs(terminal,cwd,connector.executable,connector.interactive_arguments||[]),cwd,detached:true}}
export function launchConnector(plan){const child=spawn(plan.executable,plan.arguments,{cwd:plan.cwd,shell:false,windowsHide:false,detached:true,stdio:'ignore'});child.unref();return {pid:child.pid}}
