import { existsSync, lstatSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { delimiter, dirname, extname, isAbsolute, join } from 'node:path'
import { spawn } from 'node:child_process'
export const HARNESS_IDS=['pi','claude','codex','grok']
const DEFAULT_ARGUMENTS={pi:['--print','--no-session','{prompt}'],claude:['--print','{prompt}'],codex:['exec','{prompt}'],grok:['-p','{prompt}']}
function candidates(name,env=process.env,platform=process.platform){const exts=platform==='win32'?(env.PATHEXT||'.EXE;.CMD;.BAT').split(';'):[''];return (env.PATH||'').split(platform==='win32'?';':delimiter).flatMap(dir=>exts.map(ext=>join(dir,name+ext.toLowerCase())))}
function shimInvocation(path){try{const text=readFileSync(path,'utf8'),match=text.match(/"%dp0%\\([^"\r\n]+\.js)"/i);if(!match)return null;const entry=join(dirname(path),...match[1].split(/[\\/]+/)),localNode=join(dirname(path),'node.exe'),executable=existsSync(localNode)?localNode:process.execPath;if(!existsSync(entry)||!existsSync(executable))return null;return {executable,prefix:[entry]}}catch{return null}}
function defaultConfiguration(id,executable,prefix=[]){return {schemaVersion:1,id,executable,arguments:[...prefix,...DEFAULT_ARGUMENTS[id]],promptTransport:'argument',timeoutSeconds:300,verifiedAt:null,automatic:true}}
export function detectHarnesses(env=process.env,{platform=process.platform}={}){return HARNESS_IDS.map(id=>{const found=candidates(id,env,platform).filter(path=>existsSync(path)&&lstatSync(path).isFile()),direct=found.find(path=>!['.cmd','.bat'].includes(extname(path).toLowerCase())),shim=direct?null:found.find(path=>['.cmd','.bat'].includes(extname(path).toLowerCase())),resolved=shim&&shimInvocation(shim),executable=direct||resolved?.executable||null,prefix=resolved?.prefix||[],detectedPath=direct||shim||null;return {id,detected:Boolean(detectedPath),runnable:Boolean(executable),executable,detectedPath,defaultConfiguration:executable?defaultConfiguration(id,executable,prefix):null,setupHint:resolved?'Windows command shim resolved to Node and its JavaScript entry point; shell execution remains disabled.':shim?'Windows command shim could not be resolved safely. Advanced settings can select its underlying executable.':null}})}
export function validateHarnessConfig(id,value){if(!HARNESS_IDS.includes(id))throw new Error('unknown harness');if(!value||typeof value!=='object'||typeof value.executable!=='string'||!value.executable||!isAbsolute(value.executable))throw new Error('absolute executable path required');if(!Array.isArray(value.arguments)||value.arguments.some(x=>typeof x!=='string'))throw new Error('arguments must be an array of strings');if(!['stdin','argument'].includes(value.promptTransport))throw new Error('prompt transport must be stdin or argument');const tokens=value.arguments.filter(x=>x.includes('{prompt}')).length;if(value.promptTransport==='argument'&&tokens!==1)throw new Error('argument transport requires one {prompt} token');if(value.promptTransport==='stdin'&&tokens)throw new Error('stdin transport cannot use {prompt}');return {schemaVersion:1,id,executable:value.executable,arguments:value.arguments,promptTransport:value.promptTransport,timeoutSeconds:Math.min(600,Math.max(5,Number(value.timeoutSeconds)||300)),verifiedAt:null,automatic:Boolean(value.automatic)}}
export function saveHarnessSettings(path,settings){mkdirSync(dirname(path),{recursive:true});const tmp=`${path}.tmp-${process.pid}`;writeFileSync(tmp,JSON.stringify(settings,null,2)+'\n');renameSync(tmp,path)}
export function loadHarnessSettings(path){try{const x=JSON.parse(readFileSync(path,'utf8'));return x.schemaVersion===1?x:{schemaVersion:1,harnesses:{}}}catch{return {schemaVersion:1,harnesses:{}}}}
export function runHarness(config,prompt,{cwd,timeoutMs,onData,maxStdout=1024*1024,maxStderr=65536}={}){return new Promise((resolve,reject)=>{const args=config.arguments.map(x=>x.replace('{prompt}',prompt));const child=spawn(config.executable,args,{cwd,shell:false,windowsHide:true,stdio:['pipe','pipe','pipe']});let stdout='',stderr='',done=false;const finish=(error)=>{if(done)return;done=true;clearTimeout(timer);error?reject(error):resolve({stdout,stderr,code:child.exitCode})};const overflow=kind=>{child.kill();finish(new Error(`harness ${kind} limit exceeded`))};child.stdout.on('data',d=>{if(Buffer.byteLength(stdout)+d.length>maxStdout)return overflow('output');stdout+=d;onData?.(String(d))});child.stderr.on('data',d=>{if(Buffer.byteLength(stderr)+d.length>maxStderr)return overflow('error output');stderr+=d});child.on('error',finish);child.on('close',code=>code===0?finish():finish(new Error(stderr||`harness exited ${code}`)));if(config.promptTransport==='stdin')child.stdin.end(prompt);else child.stdin.end();const timer=setTimeout(()=>{child.kill();finish(new Error('harness timed out'))},timeoutMs||config.timeoutSeconds*1000)})}
