import { createServer } from 'node:http'
import { createHash, randomBytes, randomUUID } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync, readdirSync, lstatSync } from 'node:fs'
import { basename, dirname, extname, isAbsolute, join, resolve } from 'node:path'
import { spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { listDocuments, readDocument, saveAnnotatedDocument, saveDocument } from './documents.mjs'
import { detectHarnesses, loadHarnessSettings, runHarness, saveHarnessSettings, validateHarnessConfig } from './harnesses.mjs'
import { loadLensRegistry, removeCustomLens, saveCustomLens, saveLensInstructions } from './lenses.mjs'
import { connectorLaunchPlan, launchConnector, loadConnectors, saveConnectorExtension } from './connectors.mjs'
import { annotationSchema, validateAnnotationMetadata } from './annotations.mjs'
const BASE=resolve(fileURLToPath(new URL('..',import.meta.url))), WEB=join(BASE,'web'), BIN=join(BASE,'bin','holoself.mjs'), VERSION=JSON.parse(readFileSync(join(BASE,'package.json'),'utf8')).version
const previewHash=value=>createHash('sha256').update(value.replace(/Approved: \d{4}-\d{2}-\d{2}T[^\n]+/g,'Approved: <commit-time>')).digest('hex')
function proposalPreviewData(value){const marker='--- proposed diff ---',index=value.indexOf(marker),header=index>=0?value.slice(0,index):value,diff=index>=0?value.slice(index+marker.length).trim():'';const field=name=>header.match(new RegExp(`^${name}:\\s*(.+)$`,'m'))?.[1]?.trim()||'';return {preview:value,target:field('Target'),affectedFiles:field('Affected files').split(';').map(item=>item.trim()).filter(Boolean),evidence:field('Evidence'),change:diff.split('\n').map(line=>line.startsWith('+')?line.slice(1):line).join('\n').trim()}}
const conversationDir=project=>join(resolve(project),'.holoself','conversations')
function conversationEvents(project,id){if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('invalid conversation id');const file=join(conversationDir(project),`${id}.ndjson`);if(!existsSync(file))throw new Error('conversation not found');return readFileSync(file,'utf8').split('\n').filter(Boolean).slice(-40).map(line=>JSON.parse(line))}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.svg':'image/svg+xml'}
const send=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))}
function body(req,limit=2*1024*1024){return new Promise((ok,no)=>{let value='';req.on('data',x=>{value+=x;if(value.length>limit){no(new Error('request too large'));req.destroy()}});req.on('end',()=>{try{ok(value?JSON.parse(value):{})}catch{no(new Error('invalid JSON'))}})})}
function cli(args,{stdin,allowFailure=false,timeoutMs=60000,maxStdout=2*1024*1024,maxStderr=128*1024}={}){return new Promise((ok,no)=>{const child=spawn(process.execPath,[BIN,...args],{shell:false,windowsHide:true,stdio:['pipe','pipe','pipe']});let out='',err='',done=false;const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);error?no(error):ok(value)};const overflow=kind=>{child.kill();finish(new Error(`Holoself ${kind} limit exceeded`))};child.stdout.on('data',x=>{if(Buffer.byteLength(out)+x.length>maxStdout)return overflow('output');out+=x});child.stderr.on('data',x=>{if(Buffer.byteLength(err)+x.length>maxStderr)return overflow('error output');err+=x});child.on('error',finish);child.on('close',code=>code===0||allowFailure?finish(null,{stdout:out.trim(),stderr:err.trim(),code}):finish(new Error(err.trim()||out.trim()||`command failed (${code})`)));child.stdin.end(stdin||'');const timer=setTimeout(()=>{child.kill();finish(new Error('Holoself command timed out'))},timeoutMs)})}
function readCatalog(root){try{return JSON.parse(readFileSync(join(root,'ui','catalog.json'),'utf8'))}catch{return {schemaVersion:1,spaces:[]}}}
function writeCatalog(root,value){mkdirSync(join(root,'ui'),{recursive:true});writeFileSync(join(root,'ui','catalog.json'),JSON.stringify(value,null,2)+'\n')}
function canonicalSpaceMetadata(root){const file=join(root,'context','linked-projects.md');if(!existsSync(file))return [];const text=readFileSync(file,'utf8'),blocks=text.split(/^##\s+/m).slice(1),items=[];for(const block of blocks){const [title,...rest]=block.split('\n'),body=rest.join('\n'),pathMatch=body.match(/-\s*Path:\s*`([^`]+)`/);if(!pathMatch)continue;items.push({name:title.trim(),path:resolve(pathMatch[1]),lens:body.match(/-\s*Lens:\s*([^\n]+)/)?.[1]?.trim()||null,boundary:body.match(/-\s*Boundary:\s*([^\n]+)/)?.[1]?.trim()||null})}return items}
function reconcileCatalog(root){const catalog=readCatalog(root),known=new Map(catalog.spaces.map(item=>[resolve(item.path),item])),discovered=canonicalSpaceMetadata(root);let changed=false;for(const item of discovered){const current=known.get(item.path);if(!current){catalog.spaces.push({id:randomUUID(),...item,addedAt:new Date().toISOString(),discoveredFrom:'context/linked-projects.md'});known.set(item.path,item);changed=true}else for(const key of ['name','lens','boundary'])if(item[key]&&current[key]!==item[key]){current[key]=item[key];changed=true}}if(changed)writeCatalog(root,catalog);return {...catalog,discovered:discovered.map(item=>item.path)}}
function correctionsFor(statusValue){const actions=[];for(const error of statusValue.errors||[]){if(/self path missing/i.test(error))actions.push({id:'relink',label:'Relink canonical root',safe:false,detail:error});else if(/bootstrap missing|no activated adapters|managed block drift|legacy-shim|no public skill installation|not installed/i.test(error))actions.push({id:'repair',label:'Repair activation',safe:false,detail:error})}if(statusValue.state==='configured')actions.push({id:'activate',label:'Activate space',safe:false,detail:'Install bounded startup pointers'});if(statusValue.index_fresh===false||statusValue.index?.fresh===false)actions.push({id:'index',label:'Rebuild index',safe:true,detail:'Refresh disposable search index'});return [...new Map(actions.map(action=>[action.id,action])).values()]}
function filesystemRoots(root){if(process.platform==='win32'){const drives=[];for(let code=65;code<=90;code++){const path=`${String.fromCharCode(code)}:/`;if(existsSync(path))drives.push({name:path,path})}return drives}return [{name:'/',path:'/'}]}
function folderListing(value){if(typeof value!=='string'||!isAbsolute(value))throw new Error('absolute folder path required');const path=resolve(value);if(!existsSync(path)||!lstatSync(path).isDirectory())throw new Error(`folder not found: ${path}`);const all=readdirSync(path,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&!entry.isSymbolicLink()).map(entry=>({name:entry.name,path:join(path,entry.name)})).sort((a,b)=>a.name.localeCompare(b.name)),folders=all.slice(0,250);return {path,name:basename(path)||path,parent:dirname(path)===path?null:dirname(path),folders,truncated:all.length>folders.length}}
async function status(space){try{return JSON.parse((await cli(['link','status','--project',space.path],{allowFailure:true})).stdout)}catch(e){return {project:space.path,state:'broken',errors:[e.message]}}}
export async function startWebServer({project=process.cwd(),root,port=0,host='127.0.0.1'}={}){
 if(host!=='127.0.0.1')throw new Error('web server is loopback-only');project=resolve(project);let linked=null;if(existsSync(join(project,'.holoself','link.yaml'))){const result=await cli(['link','status','--project',project],{allowFailure:true});linked=JSON.parse(result.stdout);if(!linked.self_context?.path)throw new Error(`linked project status is unavailable: ${project}`);if(!root)root=linked.self_context.path}else if(!root)throw new Error(`Workbench requires --root <canonical-self-root> when cwd is not a linked project: ${project}`);root=resolve(root);if(!existsSync(join(root,'config.json'))||!existsSync(join(root,'profile'))||!existsSync(join(root,'context')))throw new Error(`invalid canonical self root: ${root}`);if(linked&&resolve(linked.self_context.path)!==root)throw new Error(`--root does not match linked project self root: ${root}`);const catalog=readCatalog(root);if(linked&&!catalog.spaces.some(item=>resolve(item.path)===project)){catalog.spaces.push({id:randomUUID(),path:project,addedAt:new Date().toISOString()});writeCatalog(root,catalog)}const token=randomBytes(24).toString('hex'),settingsPath=()=>join(root,'ui','settings.json')
 const server=createServer(async(req,res)=>{try{
  res.setHeader('content-security-policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'");res.setHeader('x-content-type-options','nosniff');res.setHeader('referrer-policy','no-referrer')
  const url=new URL(req.url,`http://${req.headers.host||'127.0.0.1'}`), mutating=!['GET','HEAD'].includes(req.method)
  if(mutating&&(req.headers['x-holoself-token']!==token||req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`))return send(res,403,{ok:false,error:{code:'forbidden',message:'Invalid local session token'}})
  if(url.pathname==='/api/session')return send(res,200,{ok:true,data:{version:VERSION,mode:linked?'linked-project':'canonical-root',project:linked?project:null,root,lens:linked?.self_context?.default_lens||null,rootExists:true,token}})
  if(url.pathname==='/api/root/init'&&req.method==='POST'){await cli(['init','--root',root]);return send(res,200,{ok:true,data:{root}})}
  if(url.pathname==='/api/overview'){const catalog=reconcileCatalog(root),spaces=await Promise.all(catalog.spaces.map(status)),h=detectHarnesses();return send(res,200,{ok:true,data:{root,spaces,harnesses:h,documents:existsSync(root)?listDocuments(root).length:0}})}
  if(url.pathname==='/api/filesystem/roots'&&req.method==='GET')return send(res,200,{ok:true,data:{roots:filesystemRoots(root),suggested:[{name:'Canonical root',path:root},{name:'Root parent',path:dirname(root)}]}})
  if(url.pathname==='/api/filesystem/folders'&&req.method==='GET')return send(res,200,{ok:true,data:folderListing(url.searchParams.get('path'))})
  if(url.pathname==='/api/spaces/discover'&&req.method==='POST'){const c=reconcileCatalog(root);return send(res,200,{ok:true,data:{cataloged:c.spaces.length,discovered:c.discovered}})}
  if(url.pathname==='/api/spaces'&&req.method==='GET'){const c=reconcileCatalog(root);return send(res,200,{ok:true,data:await Promise.all(c.spaces.map(async x=>{const current=await status(x);return {...x,status:current,corrections:correctionsFor(current)}}))})}
  if(url.pathname==='/api/spaces'&&req.method==='POST'){const b=await body(req),path=resolve(b.path);await cli(['link','add','--project',path,'--self',root,'--lens',b.lens||'general','--yes']);const c=readCatalog(root);if(!c.spaces.some(x=>x.path===path))c.spaces.push({id:randomUUID(),path,addedAt:new Date().toISOString()});writeCatalog(root,c);return send(res,201,{ok:true,data:c.spaces.find(x=>x.path===path)})}
  const spaceRoute=url.pathname.match(/^\/api\/spaces\/([^/]+)$/);if(spaceRoute&&req.method==='DELETE'){const c=readCatalog(root),s=c.spaces.find(x=>x.id===spaceRoute[1]);if(!s)throw new Error('space not found');await cli(['link','remove','--project',s.path,'--yes']);c.spaces=c.spaces.filter(x=>x.id!==s.id);writeCatalog(root,c);return send(res,200,{ok:true,data:{removed:s.id}})}
  const sm=url.pathname.match(/^\/api\/spaces\/([^/]+)\/(activate|deactivate|repair|relink|doctor|analyze|index|context)$/);if(sm&&req.method==='POST'){const c=reconcileCatalog(root),s=c.spaces.find(x=>x.id===sm[1]);if(!s)throw new Error('space not found');const a=sm[2];if(a==='relink'){await cli(['link','remove','--project',s.path,'--yes'],{allowFailure:true});const result=await cli(['link','add','--project',s.path,'--self',root,'--lens',s.lens||'general','--yes']);return send(res,200,{ok:true,data:{output:result.stdout}})}const args=a==='analyze'?['analyze','all','--project',s.path]:a==='index'?['index','rebuild','--project',s.path]:a==='context'?['context','--project',s.path,'--json']:['link',a,'--project',s.path,'--yes'];return send(res,200,{ok:true,data:{output:(await cli(args)).stdout}})}
  if(url.pathname==='/api/lenses'&&req.method==='GET')return send(res,200,{ok:true,data:JSON.parse((await cli(['lens','list','--root',root])).stdout)})
  const li=url.pathname.match(/^\/api\/lenses\/([^/]+)\/instructions$/);if(li&&req.method==='PUT'){const b=await body(req),registry=saveLensInstructions(root,li[1],b.instructions,b.expectedHash);return send(res,200,{ok:true,data:{registry_hash:registry.registry_hash,lenses:registry.lenses}})}
  const lm=url.pathname.match(/^\/api\/lenses\/([^/]+)$/);if(lm&&req.method==='PUT'){const b=await body(req),registry=saveCustomLens(root,lm[1],b.definition,b.expectedHash);return send(res,200,{ok:true,data:{registry_hash:registry.registry_hash,lenses:registry.lenses}})}
  if(lm&&req.method==='DELETE'){const b=await body(req),registry=removeCustomLens(root,lm[1],b.expectedHash);return send(res,200,{ok:true,data:{registry_hash:registry.registry_hash,lenses:registry.lenses}})}
  if(url.pathname==='/api/annotations/schema'&&req.method==='GET'){const registry=loadLensRegistry(root);return send(res,200,{ok:true,data:annotationSchema(registry.lenses)})}
  if(url.pathname==='/api/annotations/validate'&&req.method==='POST'){const registry=loadLensRegistry(root),result=validateAnnotationMetadata((await body(req)).metadata,registry.lenses.map(lens=>lens.id),{allowLegacy:true});return send(res,200,{ok:true,data:result})}
  if(url.pathname==='/api/documents'&&req.method==='GET')return send(res,200,{ok:true,data:listDocuments(root)})
  if(url.pathname==='/api/document'&&req.method==='GET')return send(res,200,{ok:true,data:readDocument(root,url.searchParams.get('path'))})
  if(url.pathname==='/api/document'&&req.method==='PUT'){const b=await body(req),validate=async()=>{await cli(['validate','--root',root])},saved=b.metadata&&b.segments?await saveAnnotatedDocument(root,b.path,{metadata:b.metadata,segments:b.segments,expectedHash:b.expectedHash},{validate,knownLenses:loadLensRegistry(root).lenses.map(lens=>lens.id)}):await saveDocument(root,b.path,b.content,b.expectedHash,{validate});return send(res,200,{ok:true,data:saved})}
  if(url.pathname==='/api/proposals'&&req.method==='GET'){const project=url.searchParams.get('project');return send(res,200,{ok:true,data:JSON.parse((await cli(['proposals','list','--project',project])).stdout)})}
  const pp=url.pathname.match(/^\/api\/proposals\/([^/]+)\/preview$/);if(pp&&req.method==='POST'){const b=await body(req),preview=await cli(['proposals','approve',pp[1],'--project',b.project],{allowFailure:true});if(!preview.stdout.includes('--- proposed diff ---'))throw new Error(preview.stderr||'proposal preview unavailable');return send(res,200,{ok:true,data:{...proposalPreviewData(preview.stdout),previewHash:previewHash(preview.stdout)}})}
  const pm=url.pathname.match(/^\/api\/proposals\/([^/]+)\/(approve|reject|defer)$/);if(pm&&req.method==='POST'){const b=await body(req);if(pm[2]==='approve'){const current=await cli(['proposals','approve',pm[1],'--project',b.project],{allowFailure:true});if(!b.previewHash||previewHash(current.stdout)!==b.previewHash){const error=new Error('Proposal changed after review; preview it again.');error.code='STALE_PREVIEW';throw error}}return send(res,200,{ok:true,data:{output:(await cli(['proposals',pm[2],pm[1],'--project',b.project,'--yes'])).stdout}})}
  if(url.pathname==='/api/connectors'&&req.method==='GET')return send(res,200,{ok:true,data:loadConnectors(root)})
  if(url.pathname==='/api/connectors'&&req.method==='POST'){const connector=saveConnectorExtension(root,await body(req));return send(res,201,{ok:true,data:connector})}
  if(url.pathname==='/api/connectors/launch'&&req.method==='POST'){const b=await body(req),catalog=reconcileCatalog(root),space=catalog.spaces.find(item=>resolve(item.path)===resolve(b.space));if(!space)throw new Error('space is not linked');const plan=connectorLaunchPlan(loadConnectors(root),{space:space.path,connectorId:b.connectorId,terminalId:b.terminalId,mode:b.mode});return send(res,200,{ok:true,data:{...launchConnector(plan),connectorId:b.connectorId,terminalId:b.terminalId||null,mode:b.mode}})}
  if(url.pathname==='/api/harnesses'&&req.method==='GET'){const saved=loadHarnessSettings(settingsPath());return send(res,200,{ok:true,data:detectHarnesses().map(x=>({...x,configuration:saved.harnesses[x.id]||null}))})}
  const hm=url.pathname.match(/^\/api\/harnesses\/([^/]+)$/);if(hm&&req.method==='PUT'){const b=await body(req),saved=loadHarnessSettings(settingsPath()),config=validateHarnessConfig(hm[1],b);saved.harnesses[hm[1]]=config;saveHarnessSettings(settingsPath(),saved);return send(res,200,{ok:true,data:config})}
  const hv=url.pathname.match(/^\/api\/harnesses\/([^/]+)\/verify$/);if(hv&&req.method==='POST'){const saved=loadHarnessSettings(settingsPath()),detected=detectHarnesses().find(item=>item.id===hv[1]),config=saved.harnesses[hv[1]]||detected?.defaultConfiguration;if(!config)throw new Error('No safe automatic invocation found. Use advanced settings to select the executable.');await runHarness(config,'Reply only with OK',{cwd:root,timeoutMs:15000,maxStdout:65536});config.verifiedAt=new Date().toISOString();saved.harnesses[hv[1]]=config;saveHarnessSettings(settingsPath(),saved);return send(res,200,{ok:true,data:config})}
  if(url.pathname==='/api/conversations'&&req.method==='GET'){const project=url.searchParams.get('project'),dir=conversationDir(project);let items=[];if(existsSync(dir)){const {readdirSync}=await import('node:fs');items=readdirSync(dir).filter(x=>/^[0-9a-f-]{36}\.ndjson$/i.test(x)).map(name=>{const id=name.slice(0,-7),events=conversationEvents(project,id),last=events.at(-1)||{};return {id,harness:last.harness,updatedAt:last.at,turns:events.length}}).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}return send(res,200,{ok:true,data:items})}
  const cg=url.pathname.match(/^\/api\/conversations\/([0-9a-f-]{36})$/i);if(cg&&req.method==='GET')return send(res,200,{ok:true,data:{id:cg[1],events:conversationEvents(url.searchParams.get('project'),cg[1])}})
  if(url.pathname==='/api/conversation'&&req.method==='POST'){const b=await body(req),saved=loadHarnessSettings(settingsPath()),detected=detectHarnesses().find(item=>item.id===b.harness),config=saved.harnesses[b.harness]||detected?.defaultConfiguration;if(!config)throw new Error('connector unavailable');const project=resolve(b.project),id=b.id||randomUUID(),prior=b.id?conversationEvents(project,id):[],context=(await cli(['context','--project',project,'--lens',b.lens||'general','--task',String(b.message).slice(0,500),'--format','packet','--adapter',b.harness])).stdout;const history=prior.slice(-12).map(x=>`User: ${x.message}\nAssistant: ${x.response}`).join('\n\n').slice(-32000),prompt=`${context}${history?`\n\nRecent conversation:\n${history}`:''}\n\nUser request:\n${b.message}\n\nDurable self changes require a Holoself proposal and explicit approval.`;const result=await runHarness(config,prompt,{cwd:project});const dir=conversationDir(project);mkdirSync(dir,{recursive:true});appendFileSync(join(dir,`${id}.ndjson`),JSON.stringify({at:new Date().toISOString(),harness:b.harness,lens:b.lens||'general',message:b.message,response:result.stdout})+'\n');return send(res,200,{ok:true,data:{id,response:result.stdout}})}
  if(url.pathname.startsWith('/api/'))return send(res,404,{ok:false,error:{code:'not_found',message:'Unknown API route'}})
  const rel=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));if(rel.includes('..'))throw new Error('invalid path');const file=join(WEB,rel);if(!file.startsWith(WEB)||!existsSync(file)){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream'});res.end(readFileSync(file))
  }catch(error){send(res,['STALE_DOCUMENT','STALE_REGISTRY','STALE_PREVIEW'].includes(error.code)?409:400,{ok:false,error:{code:error.code||'request_failed',message:error.message,current_hash:error.current_hash}})}})
 await new Promise((ok,no)=>{server.once('error',no);server.listen(port,host,ok)});const address=server.address();return {server,url:`http://${host}:${address.port}`,token,root,project:linked?project:null,mode:linked?'linked-project':'canonical-root'}
}
